# Generated by Django 4.0.5 on 2022-06-22 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='slug',
        ),
        migrations.AlterField(
            model_name='worker',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.department'),
        ),
    ]
