# Generated by Django 4.0.5 on 2022-06-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_department_remove_worker_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(max_length=100),
        ),
    ]
