# Generated by Django 4.0.5 on 2022-06-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_department_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='hier_date',
        ),
    ]
