# Generated by Django 4.0.5 on 2022-06-22 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_remove_worker_hier_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='worker',
            name='heir_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
