# Generated by Django 4.0.5 on 2022-06-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_department_description_worker_heir_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
