# Generated by Django 4.0.5 on 2022-06-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_alter_worker_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100)),
        ),
    ]
