# Generated by Django 4.0.5 on 2022-06-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_department_slug_alter_department_department_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='slug',
            new_name='slug_dep',
        ),
    ]
