# Generated by Django 4.0.5 on 2022-06-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_rename_slug_department_slug_dep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='slug_dep',
            new_name='slug',
        ),
    ]
