# Generated by Django 4.0.5 on 2022-06-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0015_alter_worker_employee_id_alter_worker_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='employee_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
