# Generated by Django 4.0.5 on 2022-07-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0019_alter_worker_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
